modLoader = "javafml"
loaderVersion = "[36,)"
license = "GNU GPL 3.0"
[[mods]]
modId = "integratedterminalsfix"
version = "1.0"
displayName = "IntegratedTerminalsFix"
authors = "FengMing"
description = '''
Fix IntergratedTerminals dupe items bug (backport to 1.16)
'''

[[dependencies.integratedterminalsfix]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.integratedterminalsfix]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,1.17)"
ordering = "NONE"
side = "BOTH"
